# Generated by Django 5.2.3 on 2025-07-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
    ]
